import { SkillGroup } from "@/types/SkillGroup";

export const skills: SkillGroup[] = [
  {
    _id: "sg1",
    _type: "skillGroup",
    order: 1,
    name: "Programming Languages",
    skills: [
      {
        _id: "s1",
        _type: "skill",
        name: "Python",
        icon: "python",
        color: "#3776ab",
      },
      {
        _id: "s2",
        _type: "skill",
        name: "SQL",
        icon: "database",
        color: "#336791",
      },
      {
        _id: "s3",
        _type: "skill",
        name: "JavaScript",
        icon: "javascript",
        color: "#f7df1e",
      },
      {
        _id: "s4",
        _type: "skill",
        name: "TypeScript",
        icon: "typescript",
        color: "#3178c6",
      },
      {
        _id: "s24",
        _type: "skill",
        name: "Bash",
        icon: "terminal",
        color: "#4eaa25",
      },
    ],
    _createdAt: new Date().toISOString(),
    _updatedAt: new Date().toISOString(),
  },
  {
    _id: "sg2",
    _type: "skillGroup",
    order: 2,
    name: "Data Science & ML",
    skills: [
      {
        _id: "s5",
        _type: "skill",
        name: "Machine Learning",
        icon: "brain",
        color: "#f59e0b",
      },
      {
        _id: "s6",
        _type: "skill",
        name: "TensorFlow",
        icon: "tensorflow",
        color: "#ff6f00",
      },
      {
        _id: "s7",
        _type: "skill",
        name: "Scikit-learn",
        icon: "flask",
        color: "#f7931e",
      },
      {
        _id: "s8",
        _type: "skill",
        name: "Pandas",
        icon: "table",
        color: "#150458",
      },
      {
        _id: "s9",
        _type: "skill",
        name: "NumPy",
        icon: "chart",
        color: "#013243",
      },
      {
        _id: "s10",
        _type: "skill",
        name: "Statistics",
        icon: "chart-bar",
        color: "#6366f1",
      },
    ],
    _createdAt: new Date().toISOString(),
    _updatedAt: new Date().toISOString(),
  },
  {
    _id: "sg6",
    _type: "skillGroup",
    order: 3,
    name: "NLP & LLMs",
    skills: [
      {
        _id: "s25",
        _type: "skill",
        name: "LangChain",
        icon: "code",
        color: "#1C3C3C",
      },
      {
        _id: "s26",
        _type: "skill",
        name: "Hugging Face",
        icon: "brain",
        color: "#FFD21E",
      },
      {
        _id: "s27",
        _type: "skill",
        name: "Transformers",
        icon: "code",
        color: "#FF6B35",
      },
      {
        _id: "s28",
        _type: "skill",
        name: "Text Processing",
        icon: "type",
        color: "#4A5568",
      },
      {
        _id: "s29",
        _type: "skill",
        name: "Vector Embeddings",
        icon: "chart",
        color: "#5B21B6",
      },
      {
        _id: "s30",
        _type: "skill",
        name: "RAG Systems",
        icon: "brain",
        color: "#DC2626",
      },
    ],
    _createdAt: new Date().toISOString(),
    _updatedAt: new Date().toISOString(),
  },
  {
    _id: "sg7",
    _type: "skillGroup",
    order: 4,
    name: "MLOps & Deployment",
    skills: [
      {
        _id: "s31",
        _type: "skill",
        name: "Docker",
        icon: "docker",
        color: "#2496ed",
      },
      {
        _id: "s32",
        _type: "skill",
        name: "AWS",
        icon: "aws",
        color: "#ff9900",
      },
      {
        _id: "s33",
        _type: "skill",
        name: "Lambda",
        icon: "zap",
        color: "#FF9900",
      },
      {
        _id: "s34",
        _type: "skill",
        name: "API Development",
        icon: "api",
        color: "#555555",
      },
      {
        _id: "s35",
        _type: "skill",
        name: "Model Serving",
        icon: "server",
        color: "#6366f1",
      },
    ],
    _createdAt: new Date().toISOString(),
    _updatedAt: new Date().toISOString(),
  },
  {
    _id: "sg8",
    _type: "skillGroup",
    order: 5,
    name: "Data Engineering",
    skills: [
      {
        _id: "s36",
        _type: "skill",
        name: "ETL Pipelines",
        icon: "code",
        color: "#1e40af",
      },
      {
        _id: "s37",
        _type: "skill",
        name: "Data Warehousing",
        icon: "database",
        color: "#336791",
      },
      {
        _id: "s38",
        _type: "skill",
        name: "Apache Airflow",
        icon: "flow",
        color: "#017cee",
      },
      {
        _id: "s39",
        _type: "skill",
        name: "Big Data",
        icon: "chart",
        color: "#E34A33",
      },
    ],
    _createdAt: new Date().toISOString(),
    _updatedAt: new Date().toISOString(),
  },
  {
    _id: "sg3",
    _type: "skillGroup",
    order: 6,
    name: "Web & Cloud",
    skills: [
      {
        _id: "s11",
        _type: "skill",
        name: "React",
        icon: "react",
        color: "#61dafb",
      },
      {
        _id: "s12",
        _type: "skill",
        name: "Next.js",
        icon: "nextjs",
        color: "#000000",
      },
      {
        _id: "s13",
        _type: "skill",
        name: "Flask",
        icon: "flask",
        color: "#000000",
      },
      {
        _id: "s14",
        _type: "skill",
        name: "FastAPI",
        icon: "api",
        color: "#009485",
      },
      {
        _id: "s15",
        _type: "skill",
        name: "REST APIs",
        icon: "api",
        color: "#555555",
      },
      {
        _id: "s18",
        _type: "skill",
        name: "Git",
        icon: "git",
        color: "#f1502f",
      },
      {
        _id: "s19",
        _type: "skill",
        name: "CI/CD",
        icon: "gear",
        color: "#4a5568",
      },
    ],
    _createdAt: new Date().toISOString(),
    _updatedAt: new Date().toISOString(),
  },
  {
    _id: "sg5",
    _type: "skillGroup",
    order: 7,
    name: "Visualization & BI",
    skills: [
      {
        _id: "s20",
        _type: "skill",
        name: "Jupyter",
        icon: "notebook",
        color: "#f37726",
      },
      {
        _id: "s22",
        _type: "skill",
        name: "Power BI",
        icon: "chart",
        color: "#f2cc8f",
      },
      {
        _id: "s23",
        _type: "skill",
        name: "Tableau",
        icon: "chart",
        color: "#ea6e52",
      },
      {
        _id: "s40",
        _type: "skill",
        name: "Matplotlib",
        icon: "chart",
        color: "#11557c",
      },
      {
        _id: "s41",
        _type: "skill",
        name: "Seaborn",
        icon: "chart",
        color: "#4A90E2",
      },
      {
        _id: "s21",
        _type: "skill",
        name: "Excel",
        icon: "table",
        color: "#217346",
      },
    ],
    _createdAt: new Date().toISOString(),
    _updatedAt: new Date().toISOString(),
  },
];
